### ISSUE TITLE
JLINK support

### ISSUE THREAD

**Issue by sadkotheguest** [Community-PIO-CH32V/ch32-pio-projects#1]
Could you tell - is it possible to use JLINK with CH32V2xx MCUs?
Do you have configuration script?

**Comment by maxgerhardt** [comment]
Official JLinkExe does not support it and W.CH's OpenOCD version only implements the special two-wire protocol with their WCH-Link(E) adapters, so this will be a lot of work to get in.

**Comment by sadkotheguest** [comment]
Thanks for your answer.
