### ISSUE TITLE
API reference or programing guides?

### ISSUE THREAD

**Issue by kahoch** [Community-PIO-CH32V/ch32-pio-projects#4]
From the example, it appears that the code for the same “function” (or “goal”?) varies across different types of chips. For example, in the basic "blinky-none-os" examples, ch32 series is very different from  ch5x series. Even CH56x and CH57x have their differences. Where can I get the programing instruction? I tried searching on WCH's website, but it seems that there are no results.

**Comment by maxgerhardt** [comment]
I don't think there exists an API reference PDF for the NoneSDK(s) published by WCH, but you have the header files as a reference [e.g. CH56x_gpio.h](https://github.com/Community-PIO-CH32V/framework-wch-noneos-sdk/blob/main/Peripheral/ch56x/inc/CH56x_gpio.h) and the EVT examples, e.g. [ch32v003](https://github.com/openwch/ch32v003/tree/main/EVT/EXAM), [ch569](https://github.com/openwch/ch569/tree/main/EVT/EXAM), etc.

There's nothing really I can do in this repo to solve the problem of missing WCH documents though :(

**Comment by kahoch** [comment]
I see. Thank you for your work！
