### ISSUE TITLE
CH582M Compile BLE project error

### ISSUE THREAD

**Issue by vihor3** [Community-PIO-CH32V/ch32-pio-projects#6]
ERROR： users/xxx/.platformio/packages/toolchain-riscv/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld: cannot find -lCH58xBLE

I have used the latest EVT2.0 library and found that it cannot compile properly. It seems that the 'vessel' field in the library. json needs to be modified. I have tried 2.0, 2.0.0, 2.0.0, and 2.0.00, but they cannot compile correctly. CH58xBLE-LIB.h is written as CH58x_BLE-LIB_V2.0. Please guide me on how to make correct modifications

**Comment by maxgerhardt** [comment]
Can you say which project you're compiling exactly? Is it <https://github.com/Community-PIO-CH32V/ch32-pio-projects/tree/main/ble-usb-cdc-ch5xx>?

**Comment by vihor3** [comment]
[CH58X_BLE_Broadcaster_TEMPLATE.zip](https://github.com/Community-PIO-CH32V/ch32-pio-projects/files/14320554/CH58X_BLE_Broadcaster_TEMPLATE.zip)

I created my own project based on the example you mentioned. Could you please help me check where the problem lies

**Comment by maxgerhardt** [comment]
As I showcased in the example project referenced above, I specifically renamed `LIBCH58xBLE.a` to `libCH58xBLE.a` to GCC can find it in the standard way. Let's see if that is the problem here, too.

**Comment by maxgerhardt** [comment]
The zip file you've uploaded builds perfectly fine on Windows.
```
Linking .pio\build\genericCH582M\firmware.elf
Checking size .pio\build\genericCH582M\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  24.3% (used 7956 bytes from 32768 bytes)
Flash: [==        ]  23.1% (used 113296 bytes from 491520 bytes)
Building .pio\build\genericCH582M\firmware.bin
=======[SUCCESS] Took 8.27 seconds =====
```
So all probems you're having on Mac must be because of filename sensitivity. Try the suggestion I've given above.

**Comment by vihor3** [comment]
Yes, I have enabled case sensitivity. Thank you very much for your help. By the way, I would like to make a suggestion that perhaps the platformio.ini in the above example can be used as the default configuration file for new projects. Alternatively, you can explain in the document how to replace the upload firmware and enable UART output. If this is not done, people who have just used this plugin may have to study for several hours like me to correctly enable serial output and upload firmware.

**Comment by maxgerhardt** [comment]
I rely on people looking at the [platform examples](https://github.com/Community-PIO-CH32V/platform-ch32v/tree/develop/examples) or this repo, it shows blinky, UART for all chips and BLE for each BLE capable chip. They can also import these examples directly from the PIO Home screen in VSCode.

**Comment by vihor3** [comment]
There is another issue, when adding the compilation parameter DEBUG=1, turning on Link Time Optimization (LTO) will result in compilation failure, with the following information

ERRO: /Users/vihor/.platformio/packages/toolchain-riscv/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld: /Users/vihor/.platformio/packages/toolchain-riscv/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/lib/rv32imac/ilp32/libc_nano.a(lib_a-writer.o): in function `.L0 ':
(.text._write_r+0x16): undefined reference to `_write'
collect2: error: ld returned 1 exit status
*** [.pio/build/genericCH582M/firmware.elf] Error 1
