### ISSUE TITLE
CHV32 having trouble on jetson nano

### ISSUE THREAD

**Issue by Bramptonn** [Community-PIO-CH32V/ch32-pio-projects#8]
Im trying to program a chv32 chip using a jetson nano running ubuntu 20.03. However, it tells me that it has trouble finding the environment on aarch64. Does anyone know how to solve this issue?

**Comment by maxgerhardt** [comment]
Let's discuss this in https://github.com/Community-PIO-CH32V/platform-ch32v/issues/57.
